---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gotosocial
spec:
  components:
    - ../../../../components/kopiur
    - ../../../../components/oidc
    - ../../../../components/postgres/cert/
  interval: 1h
  path: ./kubernetes/apps/selfhosted/gotosocial/server
  postBuild:
    substitute:
      APP: gotosocial
      KOPIUR_CAPACITY: 10Gi
      NAMESPACE: selfhosted
      OIDC_CALLBACK: /auth/callback
      OIDC_DISABLE_PKCE: "true"
      OIDC_DISPLAY_NAME: GoToSocial
      SUBDOMAIN: social
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: selfhosted
---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: phanpy
spec:
  dependsOn:
    - name: gotosocial
      namespace: selfhosted
  interval: 1h
  path: ./kubernetes/apps/selfhosted/gotosocial/phanpy
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: selfhosted
  wait: false
