---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: anysync
spec:
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: ferretdb-app
      namespace: database
    - name: openebs
      namespace: openebs-system
  interval: 1h
  path: ./kubernetes/apps/selfhosted/anytype/sync
  postBuild:
    substitute:
      APP: anysync
      VOLSYNC_CAPACITY: 10Gi
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: selfhosted
