---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: silverbullet
spec:
  chartRef:
    kind: OCIRepository
    name: silverbullet
  interval: 1h
  values:
    controllers:
      silverbullet:
        containers:
          app:
            image:
              repository: ghcr.io/silverbulletmd/silverbullet
              tag: 2.6.1@sha256:4b56c552648dfa05a467407ec97d27151efd9dfcc4f8482acd553b32a2843a45
            env:
              SB_NAME: brume's notes
              TZ: Europe/Paris
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 100Mi
            securityContext:
              readOnlyRootFilesystem: true
              allowPrivilegeEscalation: false
              capabilities: {drop: ["ALL"]}
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: &port 3000
    route:
      app:
        forceRename: silverbullet
        hostnames:
          - "notes.mortebrume.eu"
        parentRefs:
          - name: envoy-internal
            namespace: network
          - name: envoy-external
            namespace: network
      unauth:
        hostnames:
          - "notes.mortebrume.eu"
        rules:
          - matches:
              - path:
                  type: Exact
                  value: /service_worker.js
              - path:
                  type: PathPrefix
                  value: /.client
            backendRefs:
              - identifier: app
                port: *port
        parentRefs:
          - name: envoy-internal
            namespace: network
          - name: envoy-external
            namespace: network
    persistence:
      data:
        existingClaim: silverbullet
        globalMounts:
          - path: /space
            subPath: data
