---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: qui
spec:
  components:
    - ../../../../components/oidc
    - ../../../../components/volsync
  dependsOn:
    - name: openebs
      namespace: openebs-system
    - name: media-storage
      namespace: media
  interval: 1h
  path: ./kubernetes/apps/media/qui/app
  postBuild:
    substitute:
      APP: qui
      NAMESPACE: media
      OIDC_CALLBACK: /api/auth/oidc/callback
      OIDC_GROUP: admins
      OIDC_LEGACY_CRYPTO: "true"
      OIDC_SHORT_USERNAME: "true"
      SUBDOMAIN: torrent
      VOLSYNC_CAPACITY: 2Gi
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  wait: false
