---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gpg-wkd
spec:
  chartRef:
    kind: OCIRepository
    name: gpg-wkd
  interval: 1h
  values:
    controllers:
      gpg-wkd:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/nginx/nginx-unprivileged
              tag: 1.29.8-alpine3.23@sha256:72cd9a222d01fdf47bd47ad8dc50b0221a768742b84a66c5e0b94ed13bcc6c72
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /policy
                    port: &port 8080
              readiness: *probe
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 32Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
    persistence:
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
          - path: /var/cache/nginx
      gpg-wkd:
        type: secret
        name: gpg-wkd
        globalMounts:
          - path: /usr/share/nginx/html
            readOnly: true
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - mortebrume.eu
          - openpgpkey.mortebrume.eu
        parentRefs:
          - name: envoy-external
            namespace: network
          - name: envoy-internal
            namespace: network
        rules:
          - matches:
              - path:
                  type: Exact
                  value: /.well-known/openpgpkey/hu/us5fk1nftuiuqys5t3hp9myrw3e4p3ed
              - path:
                  type: Exact
                  value: /.well-known/openpgpkey/mortebrume.eu/hu/us5fk1nftuiuqys5t3hp9myrw3e4p3ed
            filters:
              - type: URLRewrite
                urlRewrite:
                  path:
                    type: ReplaceFullPath
                    replaceFullPath: /hu
              - type: CORS
                cors: &cors
                  allowHeaders:
                    - "*"
                  allowMethods:
                    - "*"
                  allowOrigins:
                    - "*"
                  maxAge: 86400
            backendRefs:
              - identifier: app
                port: *port
          - matches:
              - path:
                  type: Exact
                  value: /.well-known/openpgpkey/policy
              - path:
                  type: Exact
                  value: /.well-known/openpgpkey/mortebrume.eu/policy
            filters:
              - type: URLRewrite
                urlRewrite:
                  path:
                    type: ReplaceFullPath
                    replaceFullPath: /policy
              - type: CORS
                cors: *cors
            backendRefs:
              - identifier: app
                port: *port
