---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Labeler

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  main:
    name: Labeler - Labeler
    runs-on: ubuntu-latest
    if: ${{ forgejo.event.pull_request.head.repo.full_name == forgejo.repository }}
    steps:
      - name: Labeler
        uses: https://github.com/actions/labeler@f27b608878404679385c85cfa523b85ccb86e213 # v6.1.0
        with:
          repo-token: ${{ secrets.MISTGAZER_TOKEN }}
          configuration-path: .forgejo/labeler.yaml
