---
port: 7880

redis:
  address: dragonfly.database.svc.cluster.local:6379
  db: 5

rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 60000
  ips:
    includes:
      - 10.20.0.0/16
  stun_servers:
    - turn.mortebrume.eu:3478
  turn_servers:
    - host: turn.mortebrume.eu
      port: 5349
      protocol: tls
      secret: "{{ .SHARED_SECRET }}"
    - host: turn.mortebrume.eu
      port: 3478
      protocol: udp
      secret: "{{ .SHARED_SECRET }}"
  use_external_ip: false
  enable_loopback_candidate: false

room:
  auto_create: false

turn:
  enabled: false

prometheus:
  port: 6789
log_level: info

keys:
  "{{ .LIVEKIT_KEY }}": "{{ .LIVEKIT_SECRET }}"
