---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: anysync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      data:
        ANY_SYNC_BUNDLE_INIT_S3_ENDPOINT: "{{ .S3_ENDPOINT }}"
        ANY_SYNC_BUNDLE_INIT_S3_REGION: "{{ .S3_REGION }}"
        AWS_ACCESS_KEY_ID: "{{ .R2_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .R2_SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: anysync
---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: anysync-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
          reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "database"
        labels:
          cnpg.io/reload: "true"
      data:
        username: "anysync"
        password: "{{ .ANYSYNC_DB_PASS }}"
        MONGO_ENDPOINT: |-
          mongodb://anysync:{{ .ANYSYNC_DB_PASS }}@ferretdb.database.svc.cluster.local/anysync
  dataFrom:
    - extract:
        key: anysync
