---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: anysync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      data:
        ANY_SYNC_BUNDLE_INIT_S3_ENDPOINT: "{{ .S3_ENDPOINT }}"
        ANY_SYNC_BUNDLE_INIT_S3_REGION: "{{ .S3_REGION }}"
        AWS_ACCESS_KEY_ID: "{{ .R2_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .R2_SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: anysync
