---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: karakeep
spec:
  chartRef:
    kind: OCIRepository
    name: karakeep
  interval: 1h
  values:
    controllers:
      karakeep:
        forceRename: karakeep
        type: statefulset # SQLite DB
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/karakeep-app/karakeep
              tag: 0.33.2@sha256:b069e4307dec06ea06d16989c6861c30a1ff208568be44ed5fb5d422cd3e950c
            env:
              BROWSER_WEB_URL: http://karakeep-chrome.selfhosted.svc.cluster.local:9222
              COREPACK_INTEGRITY_KEYS: 0
              CRAWLER_DOWNLOAD_BANNER_IMAGE: true
              CRAWLER_ENABLE_ADBLOCKER: true
              CRAWLER_STORE_SCREENSHOT: true
              DATA_DIR: /data
              DB_WAL_MODE: true
              DISABLE_NEW_RELEASE_CHECK: true
              DISABLE_PASSWORD_AUTH: true
              MEILI_ADDR: http://karakeep-meilisearch.selfhosted.svc.cluster.local:7700
              NEXTAUTH_URL: https://karakeep.mortebrume.eu
              OAUTH_CLIENT_ID: karakeep
              OAUTH_CLIENT_SECRET:
                valueFrom:
                  secretKeyRef:
                    name: kanidm-karakeep-oidc
                    key: client-secret
              OAUTH_PROVIDER_NAME: Kanidm
              OAUTH_WELLKNOWN_URL: https://idm.mortebrume.eu/oauth2/openid/karakeep/.well-known/openid-configuration
              OCR_LANGS: "eng,fra"
              S6_READ_ONLY_ROOT: 1
              S6_YES_I_WANT_A_WORLD_WRITABLE_RUN_BECAUSE_KUBERNETES: 1
            envFrom:
              - secretRef:
                  name: karakeep
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 10m
                memory: 800Mi
              limits:
                memory: 1Gi
            securityContext: &sec
              readOnlyRootFilesystem: true
              allowPrivilegeEscalation: false
              capabilities: {drop: ["ALL"]}
      chrome:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/karakeep-app/karakeep-chrome
              tag: 151.0.7922.47-r1@sha256:5b19bbb160e9ff60681a3abd97e1c4ec9f64212301410de658c3900ab7ef31e7
            command:
              - chromium-browser
            args:
              - --headless
              - --disable-gpu
              - --disable-dev-shm-usage
              - --hide-scrollbars
            resources:
              requests:
                cpu: 10m
                memory: 150Mi
              limits:
                memory: 1Gi
            securityContext: *sec
      meilisearch:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: mirror.gcr.io/getmeili/meilisearch
              tag: v1.53.0@sha256:a59e984fd90b9dee0c872cdb9183d330d71c038d7a3b35def5ca3ae7fb186fb2
            args:
              - /bin/meilisearch
              - --upgrade-db
            env:
              MEILI_NO_ANALYTICS: true
              MEILI_MASTER_KEY:
                valueFrom:
                  secretKeyRef:
                    name: karakeep
                    key: MEILI_MASTER_KEY
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 4Gi
            securityContext: *sec
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: karakeep
        forceRename: karakeep
        primary: true
        ports:
          http:
            port: 3000
      chrome:
        controller: chrome
        ports:
          http:
            port: 9222
      meilisearch:
        controller: meilisearch
        ports:
          http:
            port: 7700
    route:
      app:
        hostnames:
          - "karakeep.mortebrume.eu"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: 3000
    persistence:
      data:
        existingClaim: karakeep
        advancedMounts:
          karakeep:
            app:
              - path: /data
                subPath: karakeep
          meilisearch:
            app:
              - path: /meili_data
                subPath: meilisearch
      tmp:
        type: emptyDir
      run:
        type: emptyDir
        advancedMounts:
          karakeep:
            app:
              - path: /run
