---
# yaml-language-server: $schema=./cluster.yaml
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: homelab
spec:
  hosts:
    - role: controller+worker
      noTaints: true
      installFlags:
        - --disable-components=coredns,metrics-server
        - --cri-socket=remote:unix:///var/run/containerd/containerd.sock
      openSSH:
        address: server
  k0s:
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: Cluster
      metadata:
        name: k0s
      spec:
        api:
          address: 100.115.152.117
          onlyBindToAddress: false
          sans:
            - server
            - server.minuet-betelgeuse.ts.net
            - 100.115.152.117
            - fd7a:115c:a1e0::b901:9883
            - 127.0.0.1
            - localhost
            - ::1
          extraArgs:
            runtime-config: admissionregistration.k8s.io/v1beta1=true
        network:
          kubeProxy:
            disabled: true
          provider: custom
          podCIDR: 10.20.0.0/16
          serviceCIDR: 10.40.0.0/16
          dualStack:
            enabled: true
            IPv6podCIDR: fd00::/108
            IPv6serviceCIDR: fd01::/108
        featureGates:
          - name: ImageVolume
            enabled: true
            components:
              - "kube-apiserver"
              - "kube-controller-manager"
              - "kubelet"
          - name: MutatingAdmissionPolicy
            enabled: true
            components:
              - "kube-apiserver"
        workerProfiles:
          - name: default
            values:
              shutdownGracePeriod: 30s
              shutdownGracePeriodCriticalPods: 10s
              maxPods: 300
        storage:
          type: kine
        telemetry:
          enabled: false
