---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: blocky
spec:
  components:
    - ../../../../components/postgres/cert
  interval: 1h
  path: ./kubernetes/apps/network/blocky/app
  postBuild:
    substitute:
      APP: blocky
      DATABASE_EXTENSIONS: |
        [
          { name: timescaledb }
        ]
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: network
