---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      data:
        RENOVATE_TOKEN: "{{ .FORGEJO_PAT }}"
        RENOVATE_GITHUB_COM_TOKEN: "{{ .GITHUB_TOKEN }}"
        WEBHOOK_TOKEN: "{{ .FORGEJO_WEBHOOK_TOKEN }}"
  dataFrom:
    - extract:
        key: renovate
