---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/renovate-operator.mogenius.com/renovatejob_v1alpha1.json
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: mortebrume
  namespace: renovate
spec:
  discoveryFilters:
    - mortebrume/*
  extraEnv:
    - name: LOG_LEVEL
      value: debug
    - name: RENOVATE_ALLOWED_COMMANDS
      value: "['pnpm run bundle']"
    - name: RENOVATE_BASE_DIR
      value: /data
    - name: RENOVATE_BRANCH_PREFIX
      value: renovate-
    - name: RENOVATE_REDIS_URL
      value: "redis://dragonfly.database.svc:6379/4"
    - name: RENOVATE_REPOSITORY_CACHE
      value: "enabled"
  extraVolumes:
    - name: renovate-data
      persistentVolumeClaim:
        claimName: renovate-data
  extraVolumeMounts:
    - name: renovate-data
      mountPath: /data
  image: ghcr.io/renovatebot/renovate:43.141.6
  parallelism: 5
  provider:
    name: forgejo
    endpoint: https://code.mortebrume.eu/api/v1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  schedule: 0 * * * * # Every hour
  secretRef: renovate
  webhook:
    enabled: true
    authentication:
      enabled: true
      secretRef:
        name: renovate
        key: WEBHOOK_TOKEN
