---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: forgejo
spec:
  components:
    - ../../../../components/anubis
    - ../../../../components/postgres/cert
    - ../../../../components/volsync
  dependsOn:
    - name: openebs
      namespace: openebs-system
  interval: 1h
  path: ./kubernetes/apps/forgejo/forgejo/app
  postBuild:
    substitute:
      APP: forgejo
      ANUBIS_TARGET: "http://forgejo-http.forgejo.svc:3000"
      VOLSYNC_CAPACITY: 20Gi
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: forgejo
---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: forgejo-runner
spec:
  dependsOn:
    - name: forgejo
      namespace: forgejo
  interval: 1h
  path: ./kubernetes/apps/forgejo/forgejo/runner
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: forgejo
  wait: false
