---
containers:
  - env:
      - name: DEBIAN_FRONTEND
        value: noninteractive
    image: ghcr.io/bjw-s-labs/forgejo-runner:ubuntu-24.04@sha256:6eb274f2f87de1d9e3ac698bb044570d9c5e7b086c9775c1d6c3d54839eae54f
    imagePullPolicy: IfNotPresent
    name: main
    resources:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 256Mi
restartPolicy: Never
