---
containers:
  - env:
      - name: DEBIAN_FRONTEND
        value: noninteractive
    image: ghcr.io/bjw-s-labs/forgejo-runner:ubuntu-24.04@sha256:f50f4d33fb31032068802ebce9602c92a3830389dcc6436ed1c1ab8e9da8ebe0
    imagePullPolicy: IfNotPresent
    name: main
    resources:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 256Mi
restartPolicy: Never
