---
containers:
  - env:
      - name: DEBIAN_FRONTEND
        value: noninteractive
    image: ghcr.io/bjw-s-labs/forgejo-runner:ubuntu-24.04@sha256:3bf538f51b010aa00b30d56799b119bc45a03db3ee58a4d3a1baf078bd2f292f
    imagePullPolicy: IfNotPresent
    name: main
    resources:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 256Mi
restartPolicy: Never
