---
cache:
  enabled: true
  dir: /data/cache
container:
  docker_host: "-"
  workdir_parent: shared/workdir
host:
  workdir_parent: /data/act
kubernetes:
  namespace: forgejo
  poll_timeout: 10m
log:
  level: info
pluginsv2:
  k8s:
    path: /plugins/forgejo-runner-k8s
    options:
      namespace: forgejo
      poll_timeout: 10m
runner:
  capacity: 2
  file: /persistent/.runner
  labels:
    - ubuntu-latest:k8spod:/config/podspec-default.yaml
    - ubuntu-24.04:k8spod:/config/podspec-default.yaml
    - default:k8spod:/config/podspec-default.yaml
    - docker:k8spod:/config/podspec-dind.yaml
  timeout: 3h
