---
cache:
  enabled: true
  dir: /data/cache
container:
  docker_host: "-"
  workdir_parent: shared/workdir
host:
  workdir_parent: /data/act
kubernetes:
  namespace: forgejo
  poll_timeout: 10m
log:
  level: info
plugins:
  k8s:
    path: /plugins/forgejo-runner-k8s
    address: "unix:///plugin/forgejo-runner-k8s.sock"
    options:
      namespace: forgejo
      poll_timeout: 10m
runner:
  capacity: 2
  file: /persistent/.runner
  labels:
    - ubuntu-latest:plugin:k8s:/config/podspec-default.yaml
    - ubuntu-24.04:plugin:k8s:/config/podspec-default.yaml
    - default:plugin:k8s:/config/podspec-default.yaml
    - docker:plugin:k8s:/config/podspec-dind.yaml
  timeout: 3h
