---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: yspotify
spec:
  chartRef:
    kind: OCIRepository
    name: yspotify
  interval: 1h
  values:
    controllers:
      server:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/yooooomi/your_spotify_server
              tag: 1.19.0@sha256:a45776f2c1c24ebcd957f18de4432263907d6f0031c9b25fab3e95f25d15da0d
            env:
              API_ENDPOINT: &apiEndpoint https://ys.mortebrume.eu/api
              CLIENT_ENDPOINT: https://ys.mortebrume.eu
              PORT: &serverPort 8080
              MONGO_NO_ADMIN_RIGHTS: "true"
            envFrom:
              - secretRef:
                  name: yspotify
              - secretRef:
                  name: yspotify-db
            probes: &probes
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
            securityContext: &securityContext
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 500Mi
      web:
        containers:
          app:
            image:
              repository: ghcr.io/yooooomi/your_spotify_client
              tag: 1.19.0@sha256:935717b748f56536bd1f4e3bd2c83b71efbcdfb419fbda0345e7a17099a8d30e
            env:
              API_ENDPOINT: *apiEndpoint
            probes: *probes
            securityContext: *securityContext
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 100Mi
    service:
      server:
        controller: server
        ports:
          http:
            port: *serverPort
      web:
        controller: web
        ports:
          http:
            port: &webPort 3000
    route:
      app:
        hostnames:
          - ys.mortebrume.eu
        parentRefs:
          - name: envoy-external
            namespace: network
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /api
            filters:
              - type: URLRewrite
                urlRewrite:
                  path:
                    type: ReplacePrefixMatch
                    replacePrefixMatch: /
            backendRefs:
              - identifier: server
                port: *serverPort
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - identifier: web
                port: *webPort
