---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/gateway.envoyproxy.io/securitypolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: kyoo
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: kyoo
      sectionName: api
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: kyoo
      sectionName: video
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: kyoo
      sectionName: scanner
  extAuth:
    headersToExtAuth:
      - authorization
      - x-api-key
      - cookie
      - sec-websocket-protocol
      - x-forwarded-method
      - x-forwarded-uri
    http:
      backendRefs:
        - name: kyoo-auth
          port: 4568
      path: /auth/jwt
      headersToBackend:
        - authorization
  cors:
    allowOrigins:
      - "*"
    allowMethods:
      - GET
      - OPTIONS
    allowHeaders:
      - authorization
      - content-type
      - range
      - x-api-key
