---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: selfhosted

resources:
  - ./namespace.yaml
  - ./anytype/ks.yaml
  - ./apoci/ks.yaml
  - ./bentopdf/ks.yaml
  - ./foundry/ks.yaml
  - ./gotosocial/ks.yaml
  - ./karakeep/ks.yaml
  - ./mealie/ks.yaml
  - ./miniflux/ks.yaml
  - ./paperless/ks.yaml
  - ./publish-k8s-dashboards/ks.yaml
  - ./publish-k8s-schemas/ks.yaml
  - ./webhook/ks.yaml
