---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: silverbullet
spec:
  components:
    - ../../../../components/kopiur
    - ../../../../components/oidc/envoy
  dependsOn:
    - name: openebs
      namespace: openebs-system
  interval: 1h
  path: ./kubernetes/apps/selfhosted/silverbullet/app
  postBuild:
    substitute:
      APP: silverbullet
      KOPIUR_CAPACITY: 10Gi
      NAMESPACE: selfhosted
      OIDC_DISPLAY_NAME: Silverbullet
      OIDC_GROUP: admins
      OIDC_SCOPES: '["openid", "profile"]'
      SUBDOMAIN: notes
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: selfhosted
