server:
  verbosity: 1
  num-threads: 1
  interface: 0.0.0.0@53
  interface: ::0@53
  prefer-ip6: yes
  prefer-ip4: no
  outgoing-range: 4096
  outgoing-port-permit: 32768-60999
  msg-cache-size: 4m
  msg-cache-slabs: 1
  num-queries-per-thread: 4096
  udp-connect: yes
  rrset-cache-size: 64m
  rrset-cache-slabs: 1
  cache-min-ttl: 0
  cache-max-ttl: 86400
  infra-cache-slabs: 1
  discard-timeout: 4800
  do-ip4: yes
  do-ip6: yes
  do-udp: yes
  do-tcp: yes
  use-systemd: no
  do-daemonize: no
  access-control: 127.0.0.0/8 allow
  access-control: ::1/128 allow
  access-control: 10.0.0.0/8 allow
  access-control: fd00::/48 allow
  chroot: ""
  username: ""
  directory: "/usr/local/unbound/"
  logfile: ""
  use-syslog: no
  log-time-ascii: yes
  log-servfail: yes
  pidfile: ""
  hide-identity: yes
  hide-version: yes
  harden-short-bufsize: yes
  harden-large-queries: yes
  harden-glue: yes
  qname-minimisation: yes
  use-caps-for-id: no
  private-address: 10.0.0.0/8
  private-address: 172.16.0.0/12
  private-address: 192.168.0.0/16
  private-address: 169.254.0.0/16
  private-address: fd00::/8
  private-address: fe80::/10
  private-address: ::ffff:0:0/96
  private-domain: "cluster.local."
  domain-insecure: "cluster.local."
  do-not-query-localhost: yes
  deny-any: yes
  rrset-roundrobin: yes
  minimal-responses: yes
  module-config: "iterator"
  serve-expired: no
  neg-cache-size: 1m
  unblock-lan-zones: no
  insecure-lan-zones: yes
  so-sndbuf: 0
  so-rcvbuf: 0

remote-control:

forward-zone:
  name: "cluster.local."
  forward-addr: 10.40.0.10
  forward-addr: fd01::a

forward-zone:
  name: "."
  forward-addr: 1.0.0.1@53
  forward-addr: 1.1.1.1@53
  forward-addr: 2606:4700:4700::1001@53
  forward-addr: 2606:4700:4700::1111@53
