---
# yaml-language-server: $schema=https://www.schemastore.org/any.json
apiVersion: kubeadm.k8s.io/v1beta4
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 100.115.152.117
  bindPort: 6443
nodeRegistration:
  ignorePreflightErrors:
    - Swap
  taints: []
---
# yaml-language-server: $schema=https://www.schemastore.org/any.json
apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
clusterName: homelab
controlPlaneEndpoint: "100.115.152.117:6443"
encryptionAlgorithm: ECDSA-P384
networking:
  podSubnet: "10.20.0.0/16,fd00::/48"
  serviceSubnet: "10.40.0.0/16,fd01::/108"
apiServer:
  certSANs:
    - server
    - server.minuet-betelgeuse.ts.net
    - "100.115.152.117"
    - "fd7a:115c:a1e0::b901:9883"
    - "127.0.0.1"
    - localhost
    - "::1"
  extraArgs:
    - name: runtime-config
      value: "admissionregistration.k8s.io/v1beta1=true"
    - name: feature-gates
      value: "MutatingAdmissionPolicy=true"
    - name: oidc-issuer-url
      value: "https://auth.mortebrume.eu/application/o/kubernetes/"
    - name: oidc-client-id
      value: "kubernetes"
    - name: oidc-username-claim
      value: "email"
    - name: oidc-groups-claim
      value: "groups"
    - name: oidc-username-prefix
      value: "oidc:"
    - name: oidc-groups-prefix
      value: "oidc:"
controllerManager:
  extraArgs:
    - name: bind-address
      value: 0.0.0.0
scheduler:
  extraArgs:
    - name: bind-address
      value: 0.0.0.0
dns:
  disabled: true
proxy:
  disabled: true
etcd:
  local:
    dataDir: /var/lib/etcd
---
# yaml-language-server: $schema=https://www.schemastore.org/any.json
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
failSwapOn: false
featureGates:
  ImageVolume: true
maxPods: 300
shutdownGracePeriod: 30s
shutdownGracePeriodCriticalPods: 10s
