---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: externaldns-unifi
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      data:
        UNIFI_API_KEY: "{{ .API_KEY }}"
        UNIFI_CONSOLE_ID: "{{ .CONSOLE_ID }}"
  dataFrom:
    - extract:
        key: unifi
