---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: apoci
spec:
  chartRef:
    kind: OCIRepository
    name: apoci
  interval: 1h
  values:
    controllers:
      apoci:
        containers:
          app:
            image:
              repository: git.erwanleboucher.dev/eleboucher/apoci
              tag: 0.0.25@sha256:ea22542d9e196c1d09a0272c2b037222756f50b0af7f3962e1a7046d47374c3e
            env:
              APOCI_ACCOUNT_DOMAIN: mortebrume.eu
              APOCI_DATA_DIR: /data
              APOCI_DB_DRIVER: postgres
              APOCI_ENDPOINT: https://registry.mortebrume.eu
              APOCI_FEDERATION_AUTO_ACCEPT: mutual
              APOCI_DB_DSN:
                valueFrom:
                  secretKeyRef:
                    name: apoci-postgres
                    key: url
            envFrom:
              - secretRef:
                  name: apoci
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
            securityContext:
              readOnlyRootFilesystem: true
              allowPrivilegeEscalation: false
              capabilities: {drop: ["ALL"]}
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: &port 5000
    route:
      app:
        hostnames:
          - "registry.mortebrume.eu"
        parentRefs:
          - name: envoy-external
            namespace: network
      webfinger:
        hostnames:
          - "mortebrume.eu"
        rules:
          - matches:
              - path:
                  type: Exact
                  value: /.well-known/webfinger
                queryParams:
                  - name: resource
                    type: RegularExpression
                    value: ".*registry@.*"
            filters:
              - type: URLRewrite
                urlRewrite:
                  hostname: registry.mortebrume.eu
            backendRefs:
              - identifier: app
                port: *port
        parentRefs:
          - name: envoy-internal
            namespace: network
          - name: envoy-external
            namespace: network
    persistence:
      data:
        existingClaim: apoci
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: tmp
