---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: apoci
spec:
  chartRef:
    kind: OCIRepository
    name: apoci
  interval: 1h
  values:
    controllers:
      apoci:
        containers:
          app:
            image:
              repository: registry.erwanleboucher.dev/eleboucher/apoci
              tag: 0.0.45@sha256:1efddadc73eeaf717c749d5fe43e6b6233e66d61444397a9ce0a9c782e2f86b9
            env:
              APOCI_DB_DSN:
                valueFrom:
                  secretKeyRef:
                    name: apoci-postgres
                    key: url
            envFrom:
              - secretRef:
                  name: apoci
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 2Gi
            securityContext:
              readOnlyRootFilesystem: true
              allowPrivilegeEscalation: false
              capabilities: {drop: ["ALL"]}
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: &port 5000
    route:
      app:
        hostnames:
          - "registry.mortebrume.eu"
        parentRefs:
          - name: envoy-external
            namespace: network
      webfinger:
        hostnames:
          - "mortebrume.eu"
        rules:
          - matches:
              - path:
                  type: Exact
                  value: /.well-known/webfinger
                queryParams:
                  - name: resource
                    type: RegularExpression
                    value: ".*registry@.*"
            filters:
              - type: URLRewrite
                urlRewrite:
                  hostname: registry.mortebrume.eu
            backendRefs:
              - identifier: app
                port: *port
        parentRefs:
          - name: envoy-internal
            namespace: network
          - name: envoy-external
            namespace: network
    persistence:
      config:
        type: configMap
        name: apoci-config
        globalMounts:
          - path: /apoci/config/apoci.yaml
            subPath: apoci.yaml
      data:
        accessMode: ReadWriteOnce
        size: 15Gi
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: tmp
