---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: phanpy
spec:
  chartRef:
    kind: OCIRepository
    name: phanpy
  interval: 1h
  values:
    controllers:
      phanpy:
        containers:
          app:
            image:
              repository: ghcr.io/jjgadgets/phanpy
              tag: rolling@sha256:dc40489af8056ff6aa3c390913f06346504a1f2a91297d503f4310a3b4bd43ee
            env:
              PHANPY_WEBSITE: https://phanpy.mortebrume.eu
              PHANPY_DEFAULT_INSTANCE: mortebrume.eu
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 512Gi
            securityContext:
              readOnlyRootFilesystem: false
              allowPrivilegeEscalation: false
              # capabilities: {drop: ["ALL"]}
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: 8080
    route:
      app:
        hostnames:
          - "phanpy.mortebrume.eu"
        parentRefs:
          - name: envoy-external
            namespace: network
