---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      data:
        PAPERLESS_SECRET_KEY: "{{ .PAPERLESS_SECRET_KEY }}"
        PAPERLESS_SOCIALACCOUNT_PROVIDERS: >
          {
            "openid_connect": {
              "APPS": [
                {
                  "provider_id": "kanidm",
                  "name": "Kanidm",
                  "client_id": "paperless",
                  "secret": "{{ .PAPERLESS_OIDC_CLIENT_SECRET }}",
                  "settings": {
                    "server_url": "https://idm.mortebrume.eu/oauth2/openid/paperless/.well-known/openid-configuration",
                    "fetch_userinfo": true,
                    "oauth_pkce_enabled": true
                  }
                }
              ],
              "SCOPE": ["openid", "profile", "email"]
            }
          }
  dataFrom:
    - extract:
        key: paperless
