---
containers:
  - env:
      - name: DEBIAN_FRONTEND
        value: noninteractive
      - name: CARGO_BUILD_JOBS
        value: "4"
      - name: MAKEFLAGS
        value: "-j4"
    image: ghcr.io/bjw-s-labs/forgejo-runner:ubuntu-24.04@sha256:ddb813440c31a678989e3d0c6dc53a59e5e6750c9ccd1b858a9aca44395c5ae2
    imagePullPolicy: IfNotPresent
    name: main
    resources:
      limits:
        cpu: "6"
        memory: 12Gi
      requests:
        cpu: "1"
        memory: 2Gi
restartPolicy: Never
