---
containers:
  - env:
      - name: DEBIAN_FRONTEND
        value: noninteractive
      - name: CARGO_BUILD_JOBS
        value: "4"
      - name: MAKEFLAGS
        value: "-j4"
    image: ghcr.io/bjw-s-labs/forgejo-runner:ubuntu-24.04@sha256:12d016b9baa7e3f35e44e818beda2e4400d3b0792784488542894064301f330b
    imagePullPolicy: IfNotPresent
    name: main
    resources:
      limits:
        cpu: "6"
        memory: 12Gi
      requests:
        cpu: "1"
        memory: 2Gi
restartPolicy: Never
