---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: livekit-config
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      templateFrom:
        - configMap:
            name: livekit-configmap
            items:
              - key: config.yaml
  dataFrom:
    - extract:
        key: stunner
    - extract:
        key: livekit
---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: livekit-keys
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      data:
        LIVEKIT_KEY: "{{ .LIVEKIT_KEY }}"
        LIVEKIT_SECRET: "{{ .LIVEKIT_SECRET }}"
  dataFrom:
    - extract:
        key: livekit
