---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ${APP}-anubis
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: &app ${APP}
  interval: 1h
  path: ./kubernetes/components/anubis/app
  postBuild:
    substitute:
      APP: *app
      ANUBIS_TARGET: ${ANUBIS_TARGET}
      ANUBIS_DIFFICULTY: "${ANUBIS_DIFFICULTY:=\"4\"}"
      NAMESPACE: ${NAMESPACE:=${APP}}
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: Bucket
    name: flux-system
    namespace: flux-system
  targetNamespace: ${NAMESPACE:=${APP}}
  timeout: 5m
  wait: false
