---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sure
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      data:
        SECRET_KEY_BASE: "{{ .SECRET_KEY_BASE }}"
        ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY: "{{ .PRIMARY_KEY }}"
        ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY: "{{ .DETERMINISTIC_KEY }}"
        ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT: "{{ .DERIVATION_SALT }}"
  dataFrom:
    - extract:
        key: sure
