---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: continuwuity
spec:
  chartRef:
    kind: OCIRepository
    name: continuwuity
  interval: 1h
  values:
    controllers:
      continuwuity:
        type: statefulset # RockDB
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: forgejo.ellis.link/continuwuation/continuwuity
              tag: v26.6.2-maxperf@sha256:080802be0cb0051825fabedc694e43a3384d0cabbe428dcf4c58acd3428d8d86
            env:
              CONDUWUIT_CONFIG: "/config/continuwuity.toml"
              CONDUWUIT_PORT: &port 8008
              TZ: Europe/Paris
            envFrom:
              - secretRef:
                  name: continuwuity
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /_matrix/client/versions
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probe
            securityContext:
              readOnlyRootFilesystem: true
              allowPrivilegeEscalation: false
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: "1"
                memory: 2Gi
              limits:
                memory: 8Gi
        initContainers:
          unbound:
            restartPolicy: Always
            image:
              repository: docker.io/madnuttah/unbound
              tag: 1.25.1-3@sha256:1184c6210e56348ffdc446f31eb3108d6d0844ecfd18cf7081ca4ebe87ae8de8
            env:
              DISABLE_SET_PERMS: "true"
              HEALTHCHECK_PORT: 53
              TZ: Europe/Paris
            probes:
              liveness: &probeDns
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - /usr/local/unbound/sbin/healthcheck.sh
                  initialDelaySeconds: 15
                  periodSeconds: 60
                  timeoutSeconds: 30
                  failureThreshold: 5
              readiness: *probeDns
            securityContext:
              readOnlyRootFilesystem: true
              allowPrivilegeEscalation: false
              capabilities:
                add:
                  - NET_BIND_SERVICE
                drop:
                  - ALL
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 1Gi
    defaultPodOptions:
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - "127.0.0.1"
        searches:
          - cluster.local
        options:
          - name: ndots
            value: "1"
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: 80
            targetPort: *port
    route:
      app:
        hostnames:
          - "matrix.mortebrume.eu"
        parentRefs:
          - name: envoy-internal
            namespace: network
          - name: envoy-external
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: 80
      well-known:
        hostnames:
          - "mortebrume.eu"
        parentRefs:
          - name: envoy-internal
            namespace: network
          - name: envoy-external
            namespace: network
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /.well-known/matrix/
            backendRefs:
              - identifier: app
                port: 80
    persistence:
      data:
        existingClaim: continuwuity
        advancedMounts:
          continuwuity:
            app:
              - path: /data
      media:
        existingClaim: matrix-media
        advancedMounts:
          continuwuity:
            app:
              - path: /data/media
                subPath: media
      backups:
        size: 5Gi
        accessMode: ReadWriteOnce
        suffix: "backups"
        advancedMounts:
          continuwuity:
            app:
              - path: /backups
      config:
        type: configMap
        name: continuwuity-configmap
        advancedMounts:
          continuwuity:
            app:
              - path: /config/continuwuity.toml
                subPath: continuwuity.toml
      unbound:
        type: configMap
        name: unbound-configmap
        advancedMounts:
          continuwuity:
            unbound:
              - path: /usr/local/unbound/unbound.conf
                subPath: unbound.conf
      unbound-iana:
        type: emptyDir
        advancedMounts:
          continuwuity:
            unbound:
              - path: /usr/local/unbound/iana.d
