---
# yaml-language-server: $schema=https://schemas.mortebrume.eu/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
spec:
  chartRef:
    kind: OCIRepository
    name: forgejo
  interval: 1h
  values:
    gitea:
      admin:
        username: ""
      config:
        cache:
          ENABLED: true
          ADAPTER: redis
          HOST: redis://dragonfly.database.svc:6379/2?pool_size=100&idle_timeout=180s
        cron.archive_cleanup:
          ENABLED: true
          RUN_AT_START: true
          SCHEDULE: "@every 1h"
          OLDER_THAN: 2h
        database:
          DB_TYPE: postgres
          HOST: pooler-rw.database.svc:5432
          USER: forgejo
          NAME: forgejo
          SSL_MODE: verify-full
        indexer:
          ISSUE_INDEXER_TYPE: bleve
          REPO_INDEXER_ENABLED: true
        lfs:
          PATH: /data/git/lfs
        mailer:
          ENABLED: false
        openid:
          ENABLE_OPENID_SIGNIN: false
          ENABLE_OPENID_SIGNUP: false
        queue:
          TYPE: redis
          CONN_STR: redis://dragonfly.database.svc:6379/2?pool_size=100&idle_timeout=180s
        repository:
          DEFAULT_REPO_UNITS: repo.code,repo.releases,repo.pulls,repo.actions
          DISABLED_REPO_UNITS: repo.ext_wiki,repo.ext_issues
          DISABLE_DOWNLOAD_SOURCE_ARCHIVES: true
          ENABLE_PUSH_CREATE_USER: true
          GO_GET_CLONE_URL_PROTOCOL: ssh
          ROOT: /data/git/repositories
        repository.pull-request:
          DEFAULT_DELETE_BRANCH_AFTER_MERGE: true
          DEFAULT_MERGE_STYLE: squash
        repository.signing:
          FORMAT: ssh
          SIGNING_KEY: /data/signing/ed25519.pub
          SIGNING_NAME: code.mortebrume.eu Instance
          SIGNING_EMAIL: noreply@code.mortebrume.eu
          INITIAL_COMMIT: pubkey
          CRUD_ACTIONS: pubkey, parentsigned
          WIKI: never
          MERGES: pubkey
        server:
          APP_DATA_PATH: /data/forgejo
          ROOT_URL: https://code.mortebrume.eu
          SSH_DOMAIN: code.mortebrume.eu
          SSH_PORT: &sshPort 7717
          SSH_SERVER_HOST_KEYS: ssh/host_key
          START_SSH_SERVER: true
        service:
          ALLOW_ONLY_EXTERNAL_REGISTRATION: true
          DEFAULT_ENABLE_TIMETRACKING: false
          ENABLE_INTERNAL_SIGNIN: false
          ENABLE_PASSWORD_SIGNIN_FORM: false
          SHOW_REGISTRATION_BUTTON: false
        session:
          PROVIDER: redis
          PROVIDER_CONFIG: redis://dragonfly.database.svc:6379/2?pool_size=100&idle_timeout=180s
        webhook:
          ALLOWED_HOST_LIST: "*"
      oauth:
        - name: Authentik
          adminGroup: Forgejo-Admins
          autoDiscoveryUrl: https://auth.mortebrume.eu/application/o/forgejo/.well-known/openid-configuration
          existingSecret: forgejo-oidc
          iconUrl: https://auth.mortebrume.eu/static/dist/assets/icons/icon.png
          groupClaimName: groups
          provider: openidConnect
          scopes: profile email groups
    deployment:
      env:
        - name: PGSSLROOTCERT
          value: /var/run/secrets/root-ca/ca.crt
        - name: PGSSLCERT
          value: /var/run/secrets/postgresql/tls.crt
        - name: PGSSLKEY
          value: /var/run/secrets/postgresql/tls.key
    extraContainerVolumeMounts:
      - name: host-key
        mountPath: /data/forgejo/ssh/host_key
        subPath: host_key
        readOnly: true
      - name: postgres-forgejo
        mountPath: /var/run/secrets/postgresql
        readOnly: true
      - name: root-ca
        mountPath: /var/run/secrets/root-ca
        readOnly: true
      - name: signing-key
        mountPath: /data/signing
        readOnly: true
    extraInitVolumeMounts:
      - name: host-key
        mountPath: /data/forgejo/ssh/host_key
        subPath: host_key
        readOnly: true
      - name: postgres-forgejo
        mountPath: /var/run/secrets/postgresql
        readOnly: true
      - name: root-ca
        mountPath: /var/run/secrets/root-ca
        readOnly: true
      - name: signing-key
        mountPath: /data/signing
        readOnly: true
    extraVolumes:
      - name: host-key
        secret:
          defaultMode: 0400
          secretName: forgejo-host-key
      - name: postgres-forgejo
        secret:
          defaultMode: 0600
          secretName: postgres-forgejo-cert
      - name: root-ca
        secret:
          defaultMode: 0440
          secretName: root-ca
      - name: signing-key
        secret:
          defaultMode: 0400
          secretName: forgejo-signing-key
    image:
      rootless: true
      registry: code.forgejo.org
      repository: forgejo/forgejo
      tag: 14.0.3-rootless
    persistence:
      create: false
      claimName: forgejo
    service:
      ssh:
        port: *sshPort
    tcpRoute:
      enabled: true
      parentRefs:
        - name: envoy-external
          namespace: network
          sectionName: ssh
