---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/mcpserver_v1alpha1.json
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: mkp
spec:
  image: ghcr.io/stackloklabs/mkp/server:0.4.3
  transport: streamable-http
  mcpPort: 8080
  proxyPort: 8080
  groupRef:
    name: mcp-tools
  permissionProfile:
    type: builtin
    name: network
  serviceAccount: mkp-mcp
