---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mkp-mcp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mkp-mcp-read
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mkp-mcp-read
subjects:
  - kind: ServiceAccount
    name: mkp-mcp
    namespace: ai
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mkp-mcp-read
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["*"]
    verbs: ["get"]
