---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mealie
spec:
  chartRef:
    kind: OCIRepository
    name: mealie
  interval: 1h
  values:
    controllers:
      mealie:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/mealie-recipes/mealie
              tag: v3.16.0@sha256:74496aed2c5055e3b7b6c4e1bb9b4f16b1f566601582b258a10bae851f19ac24
            env:
              ALLOW_PASSWORD_LOGIN: "false"
              BASE_URL: https://mealie.mortebrume.eu
              DB_ENGINE: postgres
              LOG_CONFIG_OVERRIDE: /config/logconf.json
              OIDC_ADMIN_GROUP: admins@idm.mortebrume.eu
              OIDC_AUTH_ENABLED: "true"
              OIDC_AUTO_REDIRECT: "true"
              OIDC_CLIENT_ID: mealie
              OIDC_CLIENT_SECRET:
                valueFrom:
                  secretKeyRef:
                    name: kanidm-mealie-oidc
                    key: client-secret
              OIDC_CONFIGURATION_URL: https://idm.mortebrume.eu/oauth2/openid/mealie/.well-known/openid-configuration
              OIDC_PROVIDER_NAME: Kanidm
              OIDC_REMEMBER_ME: "true"
              OIDC_USER_GROUP: users@idm.mortebrume.eu
              POSTGRES_URL_OVERRIDE:
                valueFrom:
                  secretKeyRef:
                    name: mealie-postgres
                    key: url
              TZ: Europe/Paris
            envFrom:
              - secretRef:
                  name: mealie
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 50m
                memory: 256Mi
              limits:
                memory: 512Mi
            securityContext:
              readOnlyRootFilesystem: true
              allowPrivilegeEscalation: false
              capabilities: {drop: ["ALL"]}
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: &port 9000
    route:
      app:
        hostnames:
          - mealie.mortebrume.eu
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      config:
        type: configMap
        name: mealie-configmap
        globalMounts:
          - path: /config/logconf.json
            subPath: logconf.json
      data:
        existingClaim: mealie
        globalMounts:
          - path: /app/data
